databases:
  - name: reina_DB
    databaseName: reina_db
    user: reina
    region: singapore

services:
  - type: web
    name: reina
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reina_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false